### PR TITLE
please don't merge.

### PR DESCRIPTION
**Pull request by helio-frota**
before
```
new PromiseModule()
Average (mean) 2340.3130434782606
new Fidelity Promise
Average (mean) 1947.934932533733
```

after
```
new PromiseModule()
Average (mean) 2433.3409295352326
new Fidelity Promise
Average (mean) 2279.8089955022488
```

I have no idea how to name these functions x and z

### CODE REVIEW

**Comment by helio-frota** [comment]
[ as usual I forget ]
Thanks to genet [plus huilu dependency] and perf-quest [research] 
This helps to identify ^

**Comment by lance** [comment]
@helio-frota I implemented similar code locally and did not see the changes in performance that you mention here. Can you explain why simply moving these try/catch blocks out into their own functions would result in a performance boost like you are seeing?

**Comment by helio-frota** [comment]
@lance The idea was to remove the maximum catch try to avoid non optimization of functions that have try / catch.

**Comment by helio-frota** [comment]
When the test is 'stable' The difference is small.
Also I don't know if is good to extract to have a small improvement.

**Comment by helio-frota** [comment]
@lance I think we can close this.
I was trying to do something related with try catch of resolvePromise function to add more value to this PR. But without success.

**Pull request closed without merging**
